### ISSUE TITLE
getVariable() only supporting INT type result, not DOUBLE nor STRING

### ISSUE THREAD

**Issue by javier-rodas** [spark/spark-sdk-android#1] opened 2015-08-10 16:09 UTC
As seen in the **Cloud Functions** documentation, available [here](https://docs.particle.io/reference/firmware/photon/#cloud-functions), the `/v1/devices/{DEVICE_ID}/{VARIABLE}` call currently supports three data types: **INT**, **DOUBLE** and **STRING** (with a maximum string size of 622 bytes).

But the Android SDK `getVariable()` function only supports the **int type** result.
This is defined in the `int getVariable(String variableName)` function in the `/cloudsdk/src/main/java/io/particle/android/sdk/cloud/SparkDevice.java` file, and the `Responses.ReadVariableResponse` type, in the `/cloudsdk/src/main/java/io/particle/android/sdk/cloud/Responses.java` file.

Any idea on when a patch will be available to solve this issue? and the updated version in Gradle?

**Comment by jensck** [comment] 2015-09-08 22:13
You're correct, that is (clearly) wrong.  I'll try to fix this with a new release some time in the next couple weeks.  Thanks for the bug report!

**Comment by trackdork** [comment] 2015-10-16 15:14
I'd like to second this request.  It would be hugely beneficial to have the String variable type supported.  Thanks for the good work on the SDK in any case!

**Comment by idokleinman** [comment] 2015-10-20 17:11
+1

**Comment by dzhibas** [comment] 2015-10-25 23:07
+1 for double and string

**Comment by Driperpp** [comment] 2015-10-27 08:34
+1. Must be able to get string from Photon to Android app.

**Comment by jensck** [comment] 2015-11-10 17:54
This is fixed in the 0.2.2 SDK release.

**Closed as completed by jensck** 2015-11-10 17:54 UTC

**Comment by dzhibas** [comment] 2015-11-10 17:56
awesome :+1:

**Comment by trackdork** [comment] 2015-11-11 03:22
First off, thank you for the update.  I was able to get my code updated to the 2.2 release.  In investigating the changes, it looks like there is a bug now, where the INT variables (listed by ParticleDevice.getVariables() as INT object type are actually being returned by ParticleDevice.getVariable("myvariable") incorrectly as Doubles.  I can use the double value as an int value and all works as expected, but something is amiss under the hood.  Thoughts?

**Comment by jensck** [comment] 2015-11-12 04:18
I did a quick review of the code, and everything looks correct.

What does the raw JSON data look like when you get the response?

**Comment by trackdork** [comment] 2015-11-12 17:43
I took another look - part of the issue is probably my lack of understanding the full scope of the changes made.  I was previously using SparkDevice.getVariable("myvariable") when i upgraded from 1.3 to 2.2.  All I had done was fix compile errors at the time of writing the previous comment.  There isn't much in the comments of the various getXXXVariable functions... i was assuming that since getVariable() returns an Object, i could check the underlying type and process accordingly, but even though the variable type is INT (haven't checked the JSON yet) the Object class is "double".  See below for example:

``` c++
Async.executeAsync(dev, new Async.ApiWork<ParticleDevice, Object>() {
     public Object callApi(ParticleDevice particleDevice) throws ParticleCloudException, IOException 
     {
         try {
             // "myvariable" is an INT
             return particleDevice.getVariable("myvariable");
         } catch (ParticleDevice.VariableDoesNotExistException e) {
             Log.e(TAG, e.getBestMessage());
         }
         return 0;
     }

     @Override
     public void onSuccess(Object value) 
     {
          // check type here
          if (value.getClass() == Integer.class) {
               // never gets here
          }
          // NOPE: value is type = double
     }
     ...
}
```

Digging a little deeper, I replaced getVariable with getIntVariable which gives expected results.  Am I missing something here?  Perhaps getVariable isn't even the right function to use.

**Comment by jensck** [comment] 2015-11-13 03:25
First, since you asked, I would recommend using the `get<type>Variable` methods, when possible:
- it's simpler, since you don't have to cast anything yourself or do any type checks
- more importantly, your code will more clearly and succinctly state exactly what type is expected there, which is easier for other devs to read (noting that "other devs" includes "future you" :)

And thanks for the callout re: the lack of javadoc on all the `getVariable()` methods.  That'll be fixed in the next release thanks to your comment!

---

With all that out of the way, from the JSON responses I've looked at, I have a suspicion about what's happening: I believe the Particle Cloud API may be returning floating point values for _all_ numeric data.  Integers are simply treated as floating point numbers with a decimal of `.0`.

When the JSON parser sees a floating point value like that and is asked to return a generic Object, it does its best to match the type it has received.

@dmiddlecamp or @towynlin , can either of you comment on this?
